table dim_item
	lineageTag: b525b22a-ce7f-4e8d-98e1-7deb7280282b

	column serie_id
		dataType: string
		lineageTag: 621a4b59-b47b-46b8-834a-6224c9fc5c98
		summarizeBy: none
		sourceColumn: serie_id

		annotation SummarizationSetBy = Automatic

	column item
		dataType: string
		lineageTag: 6bd5a93c-7c10-40b0-b471-d7314faecb71
		summarizeBy: none
		sourceColumn: item

		annotation SummarizationSetBy = Automatic

	column unidade
		dataType: string
		lineageTag: 919c2a7f-d215-45c4-babe-0a212876c42e
		summarizeBy: none
		sourceColumn: unidade

		annotation SummarizationSetBy = Automatic

	column categoria
		dataType: string
		lineageTag: 045eaa8c-6cb4-4421-9e96-2a3e8ea0789b
		summarizeBy: none
		sourceColumn: categoria

		annotation SummarizationSetBy = Automatic

	column categoria_original
		dataType: string
		lineageTag: b2500226-010e-44e4-9ba6-f202057abf4e
		summarizeBy: none
		sourceColumn: categoria_original

		annotation SummarizationSetBy = Automatic

	column inicio
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: c98e5ae9-d37c-4395-8fca-a1b7a69ceee3
		summarizeBy: none
		sourceColumn: inicio

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column fim
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 51e7bc3b-6b2e-478c-a6d2-bbd2d8befe9b
		summarizeBy: none
		sourceColumn: fim

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column meses_publicados
		dataType: int64
		formatString: 0
		lineageTag: 4348aebc-9311-4dca-82fc-84bb01517894
		summarizeBy: none
		sourceColumn: meses_publicados

		annotation SummarizationSetBy = Automatic

	column meses_na_grade
		dataType: int64
		formatString: 0
		lineageTag: 618b4750-27bd-477d-819a-b4873e805e52
		summarizeBy: none
		sourceColumn: meses_na_grade

		annotation SummarizationSetBy = Automatic

	column meses_faltando
		dataType: int64
		formatString: 0
		lineageTag: cda31670-ed23-49d4-9fcb-0436eb467e31
		summarizeBy: none
		sourceColumn: meses_faltando

		annotation SummarizationSetBy = Automatic

	column ativa
		dataType: boolean
		lineageTag: d73ed523-50b5-45c4-a630-62140b9cdd3d
		summarizeBy: none
		sourceColumn: ativa

		annotation SummarizationSetBy = Automatic

	column serie_agregada
		dataType: boolean
		lineageTag: 8bb4d749-3f9c-4ebe-a8fc-3f998293b3bc
		summarizeBy: none
		sourceColumn: serie_agregada

		annotation SummarizationSetBy = Automatic

	column media_12_inicio
		dataType: double
		lineageTag: e2ef0249-5c3c-487c-a059-38f4fb88920f
		summarizeBy: none
		sourceColumn: media_12_inicio

		annotation SummarizationSetBy = Automatic

	column media_12_fim
		dataType: double
		lineageTag: be6118d4-4e3f-44c3-a6bd-fedc4dbcec03
		summarizeBy: none
		sourceColumn: media_12_fim

		annotation SummarizationSetBy = Automatic

	column variacao_12m_pct
		dataType: double
		lineageTag: de21544f-cd9e-4956-989a-13f16a5086cc
		summarizeBy: none
		sourceColumn: variacao_12m_pct

		annotation SummarizationSetBy = Automatic

	column motivo_exclusao
		dataType: string
		lineageTag: 77f6fd5c-c0f0-4bfa-b2e0-29ebf864d64a
		summarizeBy: none
		sourceColumn: motivo_exclusao

		annotation SummarizationSetBy = Automatic

	column vol_mensal_pct
		dataType: double
		lineageTag: 0826f665-9608-4b7a-b16f-fd642c1c8f9b
		summarizeBy: none
		sourceColumn: vol_mensal_pct

		annotation SummarizationSetBy = Automatic

	column forca_tendencia
		dataType: double
		lineageTag: aa3de191-0829-40a5-b30e-5abae342d9da
		summarizeBy: none
		sourceColumn: forca_tendencia

		annotation SummarizationSetBy = Automatic

	column forca_sazonalidade
		dataType: double
		lineageTag: dc654905-7ad7-440d-b4a5-6c05c526a068
		summarizeBy: none
		sourceColumn: forca_sazonalidade

		annotation SummarizationSetBy = Automatic

	column item_pt
		dataType: string
		lineageTag: 34005ccc-9f20-49d7-85a7-6aa94142b930
		summarizeBy: none
		sourceColumn: item_pt

		annotation SummarizationSetBy = Automatic

	partition dim_item = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents(PastaDados & "dim_item.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Cabecalhos = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    Tipos = Table.TransformColumnTypes(Cabecalhos, {{"serie_id", type text}, {"item", type text}, {"item_pt", type text}, {"unidade", type text}, {"categoria", type text}, {"categoria_original", type text}, {"inicio", type date}, {"fim", type date}, {"meses_publicados", Int64.Type}, {"meses_na_grade", Int64.Type}, {"meses_faltando", Int64.Type}, {"ativa", type logical}, {"serie_agregada", type logical}, {"media_12_inicio", type number}, {"media_12_fim", type number}, {"variacao_12m_pct", type number}, {"motivo_exclusao", type text}, {"vol_mensal_pct", type number}, {"forca_tendencia", type number}, {"forca_sazonalidade", type number}}, "en-US")
				in
				    Tipos

	annotation PBI_ResultType = Table

