table fato_precos
	lineageTag: a4e6f9b6-746e-44ab-b931-110310776a95

	column serie_id
		dataType: string
		isHidden
		lineageTag: 85816d09-549d-40b4-9b15-d687d7211953
		summarizeBy: none
		sourceColumn: serie_id

		annotation SummarizationSetBy = Automatic

	column data
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: b973a86a-a8f9-42c2-88ca-70807126ff90
		summarizeBy: none
		sourceColumn: data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column preco
		dataType: double
		lineageTag: 39bccc3c-79ae-4338-9121-e53da66d0e91
		summarizeBy: none
		sourceColumn: preco

		annotation SummarizationSetBy = Automatic

	column imputado
		dataType: boolean
		lineageTag: 0c62026b-507c-4fb2-b955-a761491d70a1
		summarizeBy: none
		sourceColumn: imputado

		annotation SummarizationSetBy = Automatic

	partition fato_precos = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents(PastaDados & "fato_precos.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Cabecalhos = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    Tipos = Table.TransformColumnTypes(Cabecalhos, {{"serie_id", type text}, {"data", type date}, {"preco", type number}, {"imputado", type logical}}, "en-US")
				in
				    Tipos

	annotation PBI_ResultType = Table

