table metricas_por_item
	lineageTag: 5bef9f33-204e-48f7-8fd5-af364b5da88a

	column serie_id
		dataType: string
		isHidden
		lineageTag: daeff03c-9625-482f-8aaf-2083ccdf4462
		summarizeBy: none
		sourceColumn: serie_id

		annotation SummarizationSetBy = Automatic

	column modelo
		dataType: string
		lineageTag: f71cbad8-6c82-431e-acf5-500e568bd826
		summarizeBy: none
		sourceColumn: modelo

		annotation SummarizationSetBy = Automatic

	column mape
		dataType: double
		lineageTag: 813f61d1-52b8-477a-811a-ea820b1fab38
		summarizeBy: none
		sourceColumn: mape

		annotation SummarizationSetBy = Automatic

	column wape
		dataType: double
		lineageTag: 91b2bcb8-1785-4dbf-8668-68b83276e271
		summarizeBy: none
		sourceColumn: wape

		annotation SummarizationSetBy = Automatic

	column n
		dataType: int64
		formatString: 0
		lineageTag: ddde73e1-0747-4398-81f7-5732cf328f12
		summarizeBy: none
		sourceColumn: n

		annotation SummarizationSetBy = Automatic

	partition metricas_por_item = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents(PastaDados & "metricas_por_item.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Cabecalhos = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    Tipos = Table.TransformColumnTypes(Cabecalhos, {{"serie_id", type text}, {"modelo", type text}, {"mape", type number}, {"wape", type number}, {"n", Int64.Type}}, "en-US")
				in
				    Tipos

	annotation PBI_ResultType = Table

