table metricas_por_categoria
	lineageTag: 62fd4e58-00bd-4d2e-997e-a1328592c8c0

	column categoria
		dataType: string
		lineageTag: 3393f096-cb5e-4fa8-9efb-407d357a275e
		summarizeBy: none
		sourceColumn: categoria

		annotation SummarizationSetBy = Automatic

	column modelo
		dataType: string
		lineageTag: bd1413cd-6bf8-4ab9-8b3c-26f566dd4703
		summarizeBy: none
		sourceColumn: modelo

		annotation SummarizationSetBy = Automatic

	column mape
		dataType: double
		lineageTag: e6ed9f5e-13a2-4a9a-a6b2-efc8ac49d974
		summarizeBy: none
		sourceColumn: mape

		annotation SummarizationSetBy = Automatic

	column wape
		dataType: double
		lineageTag: 641f7c18-7619-4838-a7ca-1634703e1e9c
		summarizeBy: none
		sourceColumn: wape

		annotation SummarizationSetBy = Automatic

	column n
		dataType: int64
		formatString: 0
		lineageTag: 5a62da49-cc7a-46e5-8f5d-d8393be77a80
		summarizeBy: none
		sourceColumn: n

		annotation SummarizationSetBy = Automatic

	column modelo_nome = SWITCH([modelo], "combinado", "GB + SARIMA", "gradient_boosting", "Gradient boosting", "random_forest", "Random forest", "ridge", "Ridge", "sarima", "SARIMA", "ets", "Holt-Winters", "ingenuo", "Repetir preço atual", "sazonal_ingenuo", "Repetir ano anterior", [modelo])
		dataType: string
		lineageTag: e1a3e44e-b464-4e4e-91fd-9221c5223817
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition metricas_por_categoria = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents(PastaDados & "metricas_por_categoria.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Cabecalhos = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    Tipos = Table.TransformColumnTypes(Cabecalhos, {{"categoria", type text}, {"modelo", type text}, {"mape", type number}, {"wape", type number}, {"n", Int64.Type}}, "en-US")
				in
				    Tipos

	annotation PBI_ResultType = Table

