table metricas_modelos
	lineageTag: 17f1c487-7d70-4300-87c8-71b42489c353

	column corte
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: d3f366e8-34f4-4934-9c5c-194f01b3eb1b
		summarizeBy: none
		sourceColumn: corte

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column modelo
		dataType: string
		lineageTag: 78cf39f9-7da6-4164-b48c-d6f75e9f7aa9
		summarizeBy: none
		sourceColumn: modelo

		annotation SummarizationSetBy = Automatic

	column mae_usd
		dataType: double
		lineageTag: 7ef95247-c594-4d83-9121-3140d2b324d2
		summarizeBy: none
		sourceColumn: mae_usd

		annotation SummarizationSetBy = Automatic

	column mape
		dataType: double
		lineageTag: 89d833ba-8077-4c95-a7ce-36c33a7f465a
		summarizeBy: none
		sourceColumn: mape

		annotation SummarizationSetBy = Automatic

	column wape
		dataType: double
		lineageTag: d1ac47bb-9ba2-4d3d-bd53-96cbf4540815
		summarizeBy: none
		sourceColumn: wape

		annotation SummarizationSetBy = Automatic

	column vies_pct
		dataType: double
		lineageTag: 965c1756-403e-41f1-8510-a8da2fa90142
		summarizeBy: none
		sourceColumn: vies_pct

		annotation SummarizationSetBy = Automatic

	column ganho_vs_ingenuo_pct
		dataType: double
		lineageTag: 089048fe-78a1-4e3d-8772-399b716ab4f4
		summarizeBy: none
		sourceColumn: ganho_vs_ingenuo_pct

		annotation SummarizationSetBy = Automatic

	column series_melhor_que_ingenuo_pct
		dataType: double
		lineageTag: 2e848a23-f85c-4085-8b59-eb623b55917a
		summarizeBy: none
		sourceColumn: series_melhor_que_ingenuo_pct

		annotation SummarizationSetBy = Automatic

	column data_execucao
		dataType: string
		lineageTag: 5aa23674-4d3c-4577-a637-23a919527686
		summarizeBy: none
		sourceColumn: data_execucao

		annotation SummarizationSetBy = Automatic

	column modelo_nome = SWITCH([modelo], "combinado", "GB + SARIMA", "gradient_boosting", "Gradient boosting", "random_forest", "Random forest", "ridge", "Ridge", "sarima", "SARIMA", "ets", "Holt-Winters", "ingenuo", "Repetir preço atual", "sazonal_ingenuo", "Repetir ano anterior", [modelo])
		dataType: string
		lineageTag: e94c587d-f9cd-4497-8a4a-2b5dea70799e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition metricas_modelos = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents(PastaDados & "metricas_modelos.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Cabecalhos = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    Tipos = Table.TransformColumnTypes(Cabecalhos, {{"corte", type date}, {"modelo", type text}, {"mae_usd", type number}, {"mape", type number}, {"wape", type number}, {"vies_pct", type number}, {"ganho_vs_ingenuo_pct", type number}, {"series_melhor_que_ingenuo_pct", type number}, {"data_execucao", type text}}, "en-US")
				in
				    Tipos

	annotation PBI_ResultType = Table

