table previsoes_teste
	lineageTag: 1d183806-0735-4efd-be9f-78d5c4b03a9e

	column serie_id
		dataType: string
		isHidden
		lineageTag: b1b229ce-2683-4684-a49d-c953819def1b
		summarizeBy: none
		sourceColumn: serie_id

		annotation SummarizationSetBy = Automatic

	column item
		dataType: string
		lineageTag: ff3ed32a-e9fa-4b4e-b41c-aaf33a679676
		summarizeBy: none
		sourceColumn: item

		annotation SummarizationSetBy = Automatic

	column categoria
		dataType: string
		lineageTag: 540e7766-f278-47af-a99f-dad3c7b31cbc
		summarizeBy: none
		sourceColumn: categoria

		annotation SummarizationSetBy = Automatic

	column data_base
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: db9c4ee9-b9a0-4722-a73c-16f7571abdab
		summarizeBy: none
		sourceColumn: data_base

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column data_alvo
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: cdf51e77-060d-4425-9159-22eb390aa074
		summarizeBy: none
		sourceColumn: data_alvo

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column preco_base
		dataType: double
		lineageTag: 8a63c753-68cd-4a9f-8b77-34cce6968620
		summarizeBy: none
		sourceColumn: preco_base

		annotation SummarizationSetBy = Automatic

	column preco_real
		dataType: double
		lineageTag: 9ad38931-8f46-425f-ab71-0f240c86ec94
		summarizeBy: none
		sourceColumn: preco_real

		annotation SummarizationSetBy = Automatic

	column modelo
		dataType: string
		lineageTag: 624fd31d-ab03-4437-8809-fe7e3e281d93
		summarizeBy: none
		sourceColumn: modelo

		annotation SummarizationSetBy = Automatic

	column preco_previsto
		dataType: double
		lineageTag: 0d6bd367-06c3-4e82-8294-070bc9d95e72
		summarizeBy: none
		sourceColumn: preco_previsto

		annotation SummarizationSetBy = Automatic

	column erro
		dataType: double
		lineageTag: 3224c459-b13c-422c-8f9d-9d1acc4eba75
		summarizeBy: none
		sourceColumn: erro

		annotation SummarizationSetBy = Automatic

	column erro_abs
		dataType: double
		lineageTag: 56019007-d14e-4571-917a-3fd83e760fcd
		summarizeBy: none
		sourceColumn: erro_abs

		annotation SummarizationSetBy = Automatic

	column erro_pct
		dataType: double
		lineageTag: 999265f7-2baf-4dcf-8129-463baf3b374d
		summarizeBy: none
		sourceColumn: erro_pct

		annotation SummarizationSetBy = Automatic

	partition previsoes_teste = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents(PastaDados & "previsoes_teste.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Cabecalhos = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    Tipos = Table.TransformColumnTypes(Cabecalhos, {{"serie_id", type text}, {"item", type text}, {"categoria", type text}, {"data_base", type date}, {"data_alvo", type date}, {"preco_base", type number}, {"preco_real", type number}, {"modelo", type text}, {"preco_previsto", type number}, {"erro", type number}, {"erro_abs", type number}, {"erro_pct", type number}}, "en-US")
				in
				    Tipos

	annotation PBI_ResultType = Table

