table previsoes_teste
	lineageTag: be4a45b1-e7dc-5152-afbb-c035b915f5c4

	column serie_id
		dataType: string
		isHidden
		lineageTag: 5966c7da-ef5b-5cab-8dff-d89ed0aa9cdb
		summarizeBy: none
		sourceColumn: serie_id

		annotation SummarizationSetBy = Automatic

	column item
		dataType: string
		lineageTag: a7a53e74-fc85-5f1d-a8b4-3156c19e2cc0
		summarizeBy: none
		sourceColumn: item

		annotation SummarizationSetBy = Automatic

	column categoria
		dataType: string
		lineageTag: 313eeb36-9c23-5ac8-b667-77a6fb30e7d1
		summarizeBy: none
		sourceColumn: categoria

		annotation SummarizationSetBy = Automatic

	column data_base
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: cf661e67-f7bd-508b-9d13-5b0fd8fb642b
		summarizeBy: none
		sourceColumn: data_base

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column data_alvo
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: aa07a2bf-f746-5c47-a968-89dd08e9f584
		summarizeBy: none
		sourceColumn: data_alvo

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column preco_base
		dataType: double
		lineageTag: 1d204a8a-42ab-5385-9df1-01af8913ced7
		summarizeBy: none
		sourceColumn: preco_base

		annotation SummarizationSetBy = Automatic

	column preco_real
		dataType: double
		lineageTag: 7f66731e-260a-50ae-b8b1-fc4096e38eb4
		summarizeBy: none
		sourceColumn: preco_real

		annotation SummarizationSetBy = Automatic

	column modelo
		dataType: string
		lineageTag: 0c579122-d294-5ce8-90e6-6a0cae30bafd
		summarizeBy: none
		sourceColumn: modelo

		annotation SummarizationSetBy = Automatic

	column preco_previsto
		dataType: double
		lineageTag: 03ef2feb-9c10-5650-bb03-706148efe5e9
		summarizeBy: none
		sourceColumn: preco_previsto

		annotation SummarizationSetBy = Automatic

	column erro
		dataType: double
		lineageTag: 642132bd-4bb1-58b4-babf-050cb4277ace
		summarizeBy: none
		sourceColumn: erro

		annotation SummarizationSetBy = Automatic

	column erro_abs
		dataType: double
		lineageTag: a32053fd-a484-5c82-86be-2fc06223e87d
		summarizeBy: none
		sourceColumn: erro_abs

		annotation SummarizationSetBy = Automatic

	column erro_pct
		dataType: double
		lineageTag: 0e6fd7e2-a72f-5ab4-afdc-2320dbe9adf0
		summarizeBy: none
		sourceColumn: erro_pct

		annotation SummarizationSetBy = Automatic

	partition previsoes_teste = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents(PastaDados & "previsoes_teste.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Cabecalhos = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    Tipos = Table.TransformColumnTypes(Cabecalhos, {{"serie_id", type text}, {"item", type text}, {"categoria", type text}, {"data_base", type date}, {"data_alvo", type date}, {"preco_base", type number}, {"preco_real", type number}, {"modelo", type text}, {"preco_previsto", type number}, {"erro", type number}, {"erro_abs", type number}, {"erro_pct", type number}}, "en-US")
				in
				    Tipos

	annotation PBI_ResultType = Table
