table previsao_futura
	lineageTag: 39e68466-5d03-4519-9405-26dd0657c315

	column serie_id
		dataType: string
		isHidden
		lineageTag: 72a77fdf-7b84-41e1-a019-586ef3a927f1
		summarizeBy: none
		sourceColumn: serie_id

		annotation SummarizationSetBy = Automatic

	column item
		dataType: string
		lineageTag: c84fbae8-dd24-4752-8d19-2110366ea571
		summarizeBy: none
		sourceColumn: item

		annotation SummarizationSetBy = Automatic

	column categoria
		dataType: string
		lineageTag: adedf8cf-72ee-40ff-bf24-57976bb61aeb
		summarizeBy: none
		sourceColumn: categoria

		annotation SummarizationSetBy = Automatic

	column data_base
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 1dc62d15-e429-454c-bcd5-b29af069b97c
		summarizeBy: none
		sourceColumn: data_base

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column data_alvo
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: ba0c2bc9-1a49-4bdc-8425-a9205fe40140
		summarizeBy: none
		sourceColumn: data_alvo

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column preco_base
		dataType: double
		lineageTag: b997f7fe-9b5d-4f34-ac15-33dc1b0a71f8
		summarizeBy: none
		sourceColumn: preco_base

		annotation SummarizationSetBy = Automatic

	column modelo
		dataType: string
		lineageTag: 78d53a49-b8fa-4af7-ac24-6c99a0f47f68
		summarizeBy: none
		sourceColumn: modelo

		annotation SummarizationSetBy = Automatic

	column horizonte_meses
		dataType: int64
		formatString: 0
		lineageTag: 34e77a7a-add5-4bc4-a46d-989ce752de7c
		summarizeBy: none
		sourceColumn: horizonte_meses

		annotation SummarizationSetBy = Automatic

	column preco_previsto
		dataType: double
		lineageTag: faa30e88-0368-44c2-a11d-50a10a1fa670
		summarizeBy: none
		sourceColumn: preco_previsto

		annotation SummarizationSetBy = Automatic

	column faixa_inferior
		dataType: double
		lineageTag: f1272945-867e-4824-8b4e-f91dbcee6648
		summarizeBy: none
		sourceColumn: faixa_inferior

		annotation SummarizationSetBy = Automatic

	column faixa_superior
		dataType: double
		lineageTag: 05927694-5c06-4a93-8fba-38977d945c32
		summarizeBy: none
		sourceColumn: faixa_superior

		annotation SummarizationSetBy = Automatic

	column variacao_prevista_pct
		dataType: double
		lineageTag: e399bc02-3809-477a-81f2-80f0f2b69ceb
		summarizeBy: none
		sourceColumn: variacao_prevista_pct

		annotation SummarizationSetBy = Automatic

	column item_pt
		dataType: string
		lineageTag: 1acbb7fe-6c04-4c84-b29d-86b9085db624
		summarizeBy: none
		sourceColumn: item_pt

		annotation SummarizationSetBy = Automatic

	partition previsao_futura = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents(PastaDados & "previsao_futura.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Cabecalhos = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    Tipos = Table.TransformColumnTypes(Cabecalhos, {{"serie_id", type text}, {"item", type text}, {"item_pt", type text}, {"categoria", type text}, {"data_base", type date}, {"data_alvo", type date}, {"preco_base", type number}, {"modelo", type text}, {"horizonte_meses", Int64.Type}, {"preco_previsto", type number}, {"faixa_inferior", type number}, {"faixa_superior", type number}, {"variacao_prevista_pct", type number}}, "en-US")
				in
				    Tipos

	annotation PBI_ResultType = Table

