table sazonalidade
	lineageTag: f84d0e5c-3aea-4aa4-8065-ac55756567ad

	column serie_id
		dataType: string
		isHidden
		lineageTag: 6c90baa2-3e3b-4f54-ae6e-b2e6bc6b575e
		summarizeBy: none
		sourceColumn: serie_id

		annotation SummarizationSetBy = Automatic

	column mes
		dataType: int64
		formatString: 0
		lineageTag: 6ba5041f-154a-4856-be6c-73ac7b907361
		summarizeBy: none
		sourceColumn: mes

		annotation SummarizationSetBy = Automatic

	column desvio_sazonal_pct
		dataType: double
		lineageTag: 401e6e52-553f-4ea1-b73b-5dfb47e87779
		summarizeBy: none
		sourceColumn: desvio_sazonal_pct

		annotation SummarizationSetBy = Automatic

	partition sazonalidade = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents(PastaDados & "sazonalidade.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Cabecalhos = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    Tipos = Table.TransformColumnTypes(Cabecalhos, {{"serie_id", type text}, {"mes", Int64.Type}, {"desvio_sazonal_pct", type number}}, "en-US")
				in
				    Tipos

	annotation PBI_ResultType = Table

