# -*- coding: utf-8 -*-
"""Grupo 1 - Aula 08 Alunos - Questões de Análise de Dados em Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16QlYrSJVxe-jEQoS0kIPkX8gZ7MCNeTR

# Aula 8: avaliação prática de pandas

**GRUPO 1: BRENO LUNA E PAULA CARLESSO**

20 perguntas sobre o banco de fraude em cartão, o mesmo caso das Aulas 2, 5, 6 e 7. Cada pergunta tem uma célula de código vazia logo abaixo,
para você escrever a resposta. Rode a célula, confira o resultado, e
cole a resposta no formulário indicado pelos professores.

**Antes de começar:** os arquivos CSV desta avaliação são baixados automaticamente de um diretório compartilhado do Google Drive ao executar as primeiras células do Notebook. A referência a `PASTA_DADOS` na célula abaixo já está configurada para apontar para o diretório temporário `/csv` criado na sua sessão do Colab.

## Preparação
"""

import gdown
import os

# Dicionário com IDs dos arquivos no Google Drive
files = {
    'cartoes.csv': '13Xf9ILhqxaIcvjq0vENJFCPD-HX-FLjM',
    'categorias.csv': '1NeAB_U66QnzRHZ1tJesP5lZ0jccXLAke',
    'clientes.csv': '1zgr0k17FdKp5aRkSd96qtLyJ9x0b4bFv',
    'contestacoes.csv': '1lSpAe8stD3JEMDJMFbiiYrQH0jYtHzT8',
    'lojistas.csv': '1vydqkbd2fONvNAfNKon9izr0pqaGBqhy',
    'transacoes.csv': '1OR3lgLjqVQZoajau2wrSExWPYc8xUsFS'
}

# Criar pasta para os CSVs para manter a estrutura
os.makedirs('csv', exist_ok=True)

print("Baixando arquivos...")
for filename, file_id in files.items():
    url = f'https://drive.google.com/uc?id={file_id}'
    output = f'csv/{filename}' if filename.endswith('.csv') else filename
    gdown.download(url, output, quiet=True)
    print(f"- {filename} baixado.")

PASTA_DADOS = "/content/csv"

import pandas as pd

pd.set_option("display.max_columns", None)
# pd.reset_options()

categorias = pd.read_csv(f"{PASTA_DADOS}/categorias.csv")
clientes = pd.read_csv(f"{PASTA_DADOS}/clientes.csv")
lojistas = pd.read_csv(f"{PASTA_DADOS}/lojistas.csv")
cartoes = pd.read_csv(f"{PASTA_DADOS}/cartoes.csv")
transacoes = pd.read_csv(f"{PASTA_DADOS}/transacoes.csv")
contestacoes = pd.read_csv(f"{PASTA_DADOS}/contestacoes.csv")
# transacoes["data_hora"] = pd.to_datetime(transacoes["data_hora"])  # responda a pergunta 2 antes de descomentar essa célula!

print("transacoes:", transacoes.shape)
print("clientes:", clientes.shape)

"""## Carregando e explorando

### Pergunta 1

Quantas transações existem na tabela `transacoes`?
"""

# escreva seu código aqui

print('Quantidade de transações:',len(transacoes))

"""### Pergunta 2

Qual o tipo de dado (`dtype`) da coluna `valor` depois de carregada? E da coluna `data_hora`, antes de qualquer conversão de tipo?
"""

# escreva seu código aqui

print('Valor:',transacoes['valor'].dtype)
print('Data_hora:',transacoes['data_hora'].dtype)

"""### Pergunta 3

Qual o valor médio das transações? E o desvio padrão?
"""

# escreva seu código aqui

print('Valor médio: ',transacoes['valor'].mean())
print('Desvio padrão: ',transacoes['valor'].std())

"""### Pergunta 4

Quantos valores ausentes (NaN) existem na coluna `telefone` da tabela `clientes`?
"""

# escreva seu código aqui

qtd_nulos = clientes['telefone'].isna().sum()
print('Quantidade de valores ausentes:',qtd_nulos)

"""## Filtrando e selecionando

### Pergunta 5

Quantas transações têm valor acima de R$1.000?
"""

# escreva seu código aqui

print('Transações acima de R$1000:',len(transacoes[transacoes['valor'] > 1000]))

"""### Pergunta 6

Quantos canais distintos existem na tabela `transacoes`, e quantas transações tem cada um?
"""

# escreva seu código aqui

print('Canais distintos:',len(transacoes['canal'].unique()))
print(transacoes['canal'].value_counts())

"""### Pergunta 7

Qual o nome do cliente com `id_cliente` igual a 1?
"""

# escreva seu código aqui

print('Nome do cliente:',clientes[clientes['id_cliente'] == 1]['nome'].values[0])

"""### Pergunta 8

Quantos lojistas distintos aparecem na tabela `transacoes`? (repare que pode ser menor que o total de lojistas cadastrados)
"""

# escreva seu código aqui

print('Lojistas distintos:',len(transacoes['id_lojista'].unique()))

"""## Agregando
---

### Pergunta 9

Qual `id_lojista` tem o maior valor total de transações somado?
"""

# escreva seu código aqui

print('Lojista com maior valor total:',transacoes.groupby('id_lojista')['valor'].sum().idxmax())

"""### Pergunta 10

Para o lojista líder da pergunta anterior, quantas transações ele tem, e qual o valor total?
"""

# escreva seu código aqui

lojista_lider_id = 168
transacoes_lojista_lider = transacoes[transacoes['id_lojista'] == lojista_lider_id]

print('Quantidade de transações para o lojista líder:', len(transacoes_lojista_lider))
print('Valor total das transações para o lojista líder:', transacoes_lojista_lider['valor'].sum())

"""### Pergunta 11

Juntando `transacoes` com `lojistas` e `categorias`, qual categoria de lojista tem o maior valor total faturado?
"""

# escreva seu código aqui

transacoes_lojistas = transacoes.merge(lojistas, on='id_lojista', how='left')
transacoes_categorias = transacoes_lojistas.merge(categorias, on='id_categoria', how='left')

categoria_maior_faturamento = transacoes_categorias.groupby('nome_y')['valor'].sum().idxmax()

print('Categoria de lojista com maior valor total faturado:', categoria_maior_faturamento)

"""### Pergunta 12

Usando `pivot_table`, qual o valor total movimentado em cada canal (presencial e online)?
"""

# escreva seu código aqui

pd.pivot_table(transacoes, values='valor', index='canal', aggfunc='sum')

"""## Juntando tabelas
---

### Pergunta 13

Juntando `transacoes`, `cartoes` e `clientes`, qual o nome do cliente que mais gastou no total, somando todas as transações dele?
"""

# escreva seu código aqui

transacoes_cartoes = transacoes.merge(cartoes, on='id_cartao', how='left')
transacoes_clientes = transacoes_cartoes.merge(clientes, on='id_cliente', how='left')

cliente_maior_gasto = transacoes_clientes.groupby('nome')['valor'].sum().idxmax()

print('Cliente que mais gastou no total:', cliente_maior_gasto)

"""### Pergunta 14

Quantos clientes nunca fizeram nenhuma transação em nenhum cartão?
"""

# escreva seu código aqui

# Encontra todos os IDs de clientes que realizaram transações
clientes_com_transacoes = cartoes[cartoes['id_cartao'].isin(transacoes['id_cartao'])]['id_cliente'].unique()

# Filtra os clientes que não estão na lista de clientes com transações
clientes_sem_transacoes = clientes[~clientes['id_cliente'].isin(clientes_com_transacoes)]

print('Quantidade de clientes sem transações:', len(clientes_sem_transacoes))

"""### Pergunta 15

Quantos lojistas nunca receberam nenhuma transação?
"""

# escreva seu código aqui

# Encontra todos os IDs de lojistas que receberam transações
lojistas_com_transacoes = transacoes['id_lojista'].unique()

# Encontra todos os IDs de lojistas na tabela lojistas
todos_lojistas = lojistas['id_lojista'].unique()

# Filtra os lojistas que não estão na lista de lojistas com transações
lojistas_sem_transacoes = lojistas[~lojistas['id_lojista'].isin(lojistas_com_transacoes)]

print('Quantidade de lojistas sem transações:', len(lojistas_sem_transacoes))

"""## Visualizando
---

### Pergunta 16

Qual o valor no percentil 95 das transações? Ou seja, abaixo de qual valor ficam 95% das transações da base?
"""

# escreva seu código aqui

print('Valor no percentil 95:', transacoes['valor'].quantile(0.95))

"""### Pergunta 17

Plote um histograma do valor das transações (com Matplotlib ou Seaborn). Olhando o gráfico, a distribuição é simétrica ou puxada para a direita (cauda longa de valores altos)?
"""

# escreva seu código aqui

import matplotlib.pyplot as plt

plt.hist(transacoes['valor'], bins=20)
plt.xlabel('Valor')
plt.ylabel('Frequência')
plt.title('Histograma do Valor das Transações')
plt.show()

"""## Investigação

### Pergunta 18

Calcule a taxa de contestação (proporção de transações com status "contestada") de cada lojista. Qual lojista tem a maior taxa, e qual é essa taxa, aproximadamente?
"""

contestacoes

# escreva seu código aqui

# Identificar todas as transações que aparecem na tabela de contestacoes
id_transacoes_contestadas = contestacoes['id_transacao'].unique()

# Filtrar o DataFrame de transacoes para obter apenas as transações contestadas
transacoes_contestadas_filtrado = transacoes[transacoes['id_transacao'].isin(id_transacoes_contestadas)]

# Calcular o número total de transações por lojista
total_transacoes_por_lojista = transacoes.groupby('id_lojista').size()

# Calcular o número de transações contestadas por lojista
transacoes_contestadas_por_lojista = transacoes_contestadas_filtrado.groupby('id_lojista').size()

# Calcular a taxa de contestação por lojista
# Usar fillna(0) para lojistas que não tiveram transações contestadas
taxa_contestacao = (transacoes_contestadas_por_lojista / total_transacoes_por_lojista).fillna(0)

# Encontrar o lojista com a maior taxa de contestação
lojista_maior_taxa = taxa_contestacao.idxmax()
maior_taxa = taxa_contestacao.max()

print(f"Lojista com a maior taxa de contestação: {lojista_maior_taxa}")
print(f"Maior taxa de contestação: {maior_taxa:.4f}")

"""### Pergunta 19

Para o lojista mais suspeito da pergunta anterior, qual o percentual das transações dele que acontece entre 1h e 3h da manhã?
"""

# escreva seu código aqui

# Converter 'data_hora' para datetime se ainda não foi feito
if transacoes['data_hora'].dtype == 'object':
    transacoes['data_hora'] = pd.to_datetime(transacoes['data_hora'])

# Lojista mais suspeito (ID 141)
lojista_suspeito_id = 141

# Filtrar transações para o lojista suspeito e criar uma cópia explícita
transacoes_lojista_suspeito = transacoes[transacoes['id_lojista'] == lojista_suspeito_id].copy()

# Extrair a hora da coluna 'data_hora'
transacoes_lojista_suspeito['hora'] = transacoes_lojista_suspeito['data_hora'].dt.hour

# Filtrar transações entre 1h e 3h da manhã (horas 1 e 2)
transacoes_madrugada = transacoes_lojista_suspeito[
    (transacoes_lojista_suspeito['hora'] >= 1) & (transacoes_lojista_suspeito['hora'] < 3)
]

# Calcular o percentual
percentual_madrugada = (len(transacoes_madrugada) / len(transacoes_lojista_suspeito)) * 100

print(f"Para o lojista {lojista_suspeito_id}, {percentual_madrugada:.2f}% das transações ocorrem entre 1h e 3h da manhã.")

"""### Pergunta 20

Procure por "teste de cartão": cartões com 4 ou mais transações de valor até R$5, no mesmo lojista, no mesmo dia. Quantos cartões distintos mostram esse padrão?
"""

# escreva seu código aqui

# Converter 'data_hora' para datetime se ainda não foi feito
if transacoes['data_hora'].dtype == 'object':
    transacoes['data_hora'] = pd.to_datetime(transacoes['data_hora'])

# Filtrar transações com valor até R$5 e criar uma cópia explícita
transacoes_valor_baixo = transacoes[transacoes['valor'] <= 5].copy()

# Extrair a data da transação
transacoes_valor_baixo['data'] = transacoes_valor_baixo['data_hora'].dt.date

# Agrupar por id_cartao, id_lojista e data, e contar as transações
padrao_teste_cartao = transacoes_valor_baixo.groupby(['id_cartao', 'id_lojista', 'data']).size()

# Filtrar grupos com 4 ou mais transações
cartoes_com_padrao = padrao_teste_cartao[padrao_teste_cartao >= 4]

# Contar o número de id_cartao distintos que mostram esse padrão
num_cartoes_distintos = cartoes_com_padrao.reset_index()['id_cartao'].nunique()

print(f"Número de cartões distintos que mostram o padrão de 'teste de cartão': {num_cartoes_distintos}")

"""## Pronto

Confira se respondeu todas as 20 perguntas, e cole os resultados no
formulário. Se alguma pergunta travar, escreva no chat com o número
da pergunta, não precisa esperar até o final.
"""